// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;

    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJewUIVpcdwTP1mOefAid8APr7wCYAdpY',
    appId: '1:740354406566:web:f32695adfa76342b681c67',
    messagingSenderId: '740354406566',
    projectId: 'car-rental-app-b4da0',
    authDomain: 'car-rental-app-b4da0.firebaseapp.com',
    storageBucket: 'car-rental-app-b4da0.firebasestorage.app',
    measurementId: 'G-H18Z1L6WP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHT8Ygj0Xa6AztfYU4nNZgcjqrT7jc33w',
    appId: '1:740354406566:android:0c4b9c00ff986ebb681c67',
    messagingSenderId: '740354406566',
    projectId: 'car-rental-app-b4da0',
    storageBucket: 'car-rental-app-b4da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSefMaYES1sHRVvRUCnj7udKdTycCX8d0',
    appId: '1:740354406566:ios:604aa42e7ab6852c681c67',
    messagingSenderId: '740354406566',
    projectId: 'car-rental-app-b4da0',
    storageBucket: 'car-rental-app-b4da0.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSefMaYES1sHRVvRUCnj7udKdTycCX8d0',
    appId: '1:740354406566:ios:604aa42e7ab6852c681c67',
    messagingSenderId: '740354406566',
    projectId: 'car-rental-app-b4da0',
    storageBucket: 'car-rental-app-b4da0.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJewUIVpcdwTP1mOefAid8APr7wCYAdpY',
    appId: '1:740354406566:web:d3c2ad94c74fb87d681c67',
    messagingSenderId: '740354406566',
    projectId: 'car-rental-app-b4da0',
    authDomain: 'car-rental-app-b4da0.firebaseapp.com',
    storageBucket: 'car-rental-app-b4da0.firebasestorage.app',
    measurementId: 'G-F2GGHMZTZ2',
  );
}
